version: "2.0"
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - container-volume:/var/lib/mysql
      - ./db/migration.sql:/docker-entrypoint-initdb.d/1.sql
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "frontend"
      - "backend"
  backend:
    image: node:19
    volumes:
      - ./backend:/app
    depends_on:
      - "db"
    working_dir: /app
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_SCHEMA=facilities
      - DEMO_USER_ID=2
    command: bash -c "npm ci && npm run serve"
  frontend:
    image: node:19
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: bash -c "npm ci && npm run start"
  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - "db"
volumes:
  container-volume: